// ─── Tipi di Replica ASG ───────────────────────────────────────
export const FIREARM_TYPES = [
  "AEG",
  "AEP",
  "GBB_PISTOLA",
  "GBB_FUCILE",
  "HPA",
  "NGRS",
  "GAS_NBB",
  "SPRINGER",
  "DMR_SNIPER",
] as const;

export type FirearmType = (typeof FIREARM_TYPES)[number];

export const FIREARM_TYPE_LABELS: Record<FirearmType, string> = {
  AEG: "AEG (Elettrica)",
  AEP: "AEP (Pistola Elettrica)",
  GBB_PISTOLA: "GBB Pistola",
  GBB_FUCILE: "GBB Fucile",
  HPA: "HPA (High Pressure Air)",
  NGRS: "NGRS (Next Gen Recoil)",
  GAS_NBB: "Gas Non-Blowback",
  SPRINGER: "Springer",
  DMR_SNIPER: "DMR / Sniper",
};

// ─── Slot Accessori ────────────────────────────────────────────
export const SLOT_TYPES = [
  "CANNA",
  "HOP_UP",
  "SILENZIATORE",
  "CALCIO",
  "BUFFER_TUBE",
  "IMPUGNATURA",
  "OTTICA",
  "MOUNT_OTTICA",
  "SOTTOCANNA",
  "CARICATORE",
  "TORCIA",
  "LASER",
  "LEVA_ARMAMENTO",
  "GRILLETTO",
  "GEARBOX",
  "MOTORE",
  "MOSFET",
  "BATTERIA",
  "REGOLATORE_HPA",
  "SLIDE",
  "FRAME",
  "TRACOLLA",
  "BIPOD",
  "COMPENSATORE",
] as const;

export type SlotType = (typeof SLOT_TYPES)[number];

export const SLOT_TYPE_LABELS: Record<SlotType, string> = {
  CANNA: "Canna",
  HOP_UP: "Hop-Up",
  SILENZIATORE: "Silenziatore / Tracer Unit",
  CALCIO: "Calcio",
  BUFFER_TUBE: "Buffer Tube",
  IMPUGNATURA: "Impugnatura",
  OTTICA: "Ottica",
  MOUNT_OTTICA: "Mount Ottica",
  SOTTOCANNA: "Sottocanna",
  CARICATORE: "Caricatore",
  TORCIA: "Torcia",
  LASER: "Laser",
  LEVA_ARMAMENTO: "Leva di Armamento",
  GRILLETTO: "Grilletto",
  GEARBOX: "Gearbox",
  MOTORE: "Motore",
  MOSFET: "MOSFET / ETU",
  BATTERIA: "Batteria",
  REGOLATORE_HPA: "Regolatore HPA",
  SLIDE: "Slide",
  FRAME: "Frame",
  TRACOLLA: "Tracolla",
  BIPOD: "Bipod",
  COMPENSATORE: "Compensatore",
};

export const CUSTOM_SLOT_PREFIX = "CUSTOM:";

// Slot disponibili per tipo di replica
export const SLOTS_BY_FIREARM_TYPE: Record<FirearmType, SlotType[]> = {
  AEG: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "BUFFER_TUBE",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "SOTTOCANNA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "LEVA_ARMAMENTO",
    "GRILLETTO",
    "GEARBOX",
    "MOTORE",
    "MOSFET",
    "BATTERIA",
    "TRACOLLA",
    "BIPOD",
    "COMPENSATORE",
  ],
  AEP: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "GRILLETTO",
    "GEARBOX",
    "MOTORE",
    "MOSFET",
    "BATTERIA",
    "COMPENSATORE",
  ],
  GBB_PISTOLA: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "SLIDE",
    "FRAME",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "GRILLETTO",
    "COMPENSATORE",
  ],
  GBB_FUCILE: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "BUFFER_TUBE",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "SOTTOCANNA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "LEVA_ARMAMENTO",
    "GRILLETTO",
    "TRACOLLA",
    "BIPOD",
    "COMPENSATORE",
  ],
  HPA: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "BUFFER_TUBE",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "SOTTOCANNA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "GRILLETTO",
    "REGOLATORE_HPA",
    "TRACOLLA",
    "BIPOD",
    "COMPENSATORE",
  ],
  NGRS: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "BUFFER_TUBE",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "SOTTOCANNA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "LEVA_ARMAMENTO",
    "GRILLETTO",
    "GEARBOX",
    "MOTORE",
    "MOSFET",
    "BATTERIA",
    "TRACOLLA",
    "BIPOD",
    "COMPENSATORE",
  ],
  GAS_NBB: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "CARICATORE",
    "TORCIA",
    "LASER",
    "GRILLETTO",
    "TRACOLLA",
    "BIPOD",
  ],
  SPRINGER: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "CARICATORE",
    "GRILLETTO",
    "BIPOD",
    "TRACOLLA",
  ],
  DMR_SNIPER: [
    "CANNA",
    "HOP_UP",
    "SILENZIATORE",
    "CALCIO",
    "IMPUGNATURA",
    "OTTICA",
    "MOUNT_OTTICA",
    "CARICATORE",
    "GRILLETTO",
    "BIPOD",
    "TRACOLLA",
  ],
};

export const SUGGESTED_SLOTS_BY_FIREARM_TYPE: Record<FirearmType, SlotType[]> = {
  AEG:        ["OTTICA", "CANNA", "SILENZIATORE", "CALCIO", "MOSFET", "BATTERIA"],
  AEP:        ["OTTICA", "CANNA", "SILENZIATORE", "BATTERIA", "TORCIA"],
  GBB_PISTOLA:["OTTICA", "CANNA", "SLIDE", "TORCIA", "LASER", "SILENZIATORE"],
  GBB_FUCILE: ["OTTICA", "CANNA", "SILENZIATORE", "CALCIO", "IMPUGNATURA"],
  HPA:        ["OTTICA", "CANNA", "REGOLATORE_HPA", "CALCIO", "BIPOD", "SILENZIATORE"],
  NGRS:       ["OTTICA", "CANNA", "SILENZIATORE", "CALCIO", "MOSFET", "BATTERIA"],
  GAS_NBB:    ["OTTICA", "CANNA", "SILENZIATORE", "CALCIO", "BIPOD"],
  SPRINGER:   ["OTTICA", "CANNA", "CALCIO", "BIPOD"],
  DMR_SNIPER: ["OTTICA", "MOUNT_OTTICA", "CANNA", "CALCIO", "BIPOD", "SILENZIATORE"],
};

// ─── Tipi di Transazione BBS ───────────────────────────────────
export const TRANSACTION_TYPES = [
  "PURCHASE",
  "RANGE_USE",
  "TRANSFER_OUT",
  "INVENTORY_CORRECTION",
  "EXPENDED",
] as const;

export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export const TRANSACTION_TYPE_LABELS: Record<TransactionType, string> = {
  PURCHASE: "Acquisto",
  RANGE_USE: "Uso in Campo",
  TRANSFER_OUT: "Trasferimento",
  INVENTORY_CORRECTION: "Correzione Inventario",
  EXPENDED: "Consumate",
};

// ─── Grammature BBS ────────────────────────────────────────────
export const COMMON_CALIBERS = [
  "0.20g",
  "0.23g",
  "0.25g",
  "0.28g",
  "0.30g",
  "0.32g",
  "0.36g",
  "0.40g",
  "0.43g",
  "0.45g",
  "0.50g",
];

// ─── Tipi di BBS ───────────────────────────────────────────────
export const BULLET_TYPES = [
  "Standard",
  "Bio",
  "Tracciante",
  "Bio Tracciante",
] as const;

export type BulletType = (typeof BULLET_TYPES)[number];

// ─── Tipi di Batteria ──────────────────────────────────────────
export const BATTERY_TYPES = [
  "LiPo 7.4V",
  "LiPo 11.1V",
  "NiMH 8.4V",
  "NiMH 9.6V",
  "Li-Ion 7.4V",
  "Li-Ion 11.1V",
  "Altra",
] as const;

export type BatteryType = (typeof BATTERY_TYPES)[number];
